name: Continuous Integration
on: [pull_request]

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.14.2'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: NPM clean install
        run: npm ci

      - name: Type checking
        run: npm run typecheck

      - name: Lint
        run: npm run lint
